dist: trusty
sudo: false
language: go

services:
  - redis-server

go:
  - 1.11.x
  - 1.12.x
  - tip

matrix:
  allow_failures:
    - go: tip

env:
  - GO111MODULE=on

script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d .)
  - go vet .
  - go test -v -race ./...
